package expr

import "strings"

// Reference returns a concise Markdown reference for the expression
// language, served by the MCP layer as get_dsl_reference("expressions").
func Reference() string {
	lines := []string{
		"# Expression reference",
		"",
		"Sapien flow expressions are CEL (Common Expression Language). `assert`,",
		"`extract`, and `until` are bare CEL; `${...}` inside any other string",
		"interpolates a CEL expression.",
		"",
		"## Roots",
		"",
		"- `inputs` - flow inputs, by name.",
		"- `env` - environment variables (strings).",
		"- `steps.<id>` - a prior step's `{request, status, headers, body, latency_ms, out}`,",
		"  always its LATEST execution; a loop block's own id additionally has",
		"  `{count, iterations}` (§ Loop blocks below).",
		"- Inside a step's own `assert`/`extract`/`until` only: `status` (int),",
		"  `headers` (map, lower-cased keys), `body` (any), `latency_ms` (double),",
		"  `request` (`{method, url, headers, body}`), `out` (this step's extracted",
		"  values so far).",
		"- `iter.item`/`iter.index` - only inside a loop block's own nested-step",
		"  expressions (§ Loop blocks below); `item` is unset for a `repeat` block.",
		"- `secret.NAME` is not a root. It may only appear inside a `${...}`",
		"  template in `headers`/`auth` values, is substituted before the",
		"  template is evaluated, and never appears in a run record.",
		"",
		"## Operators and functions",
		"",
		"Standard CEL: `==` `!=` `<` `<=` `>` `>=` `&&` `||` `!` `in`, plus `size()`,",
		"`has()`, and (via the strings extension) `.contains()`, `.matches()`,",
		"`.startsWith()`, `.endsWith()`. Numeric comparisons work across int and",
		"double (`latency_ms < 2000` compares a double to an int literal). A",
		"missing map key is an error, not `null` - see Notes below.",
		"",
		"```cel",
		"status == 201",
		"latency_ms < 2000",
		"body.online == true",
		"body.count == 2",
		"has(body.riderId)",
		"body.items.size() > 0",
		"body.name.contains(\"QCOM\")",
		"body.name.matches(\"^Q.*M$\")",
		"\"a\" in [\"a\", \"b\"]",
		"steps.create.body.orderId == \"ord_1\"",
		"steps.create.status == 201",
		"```",
		"",
		"## Interpolation",
		"",
		"`${...}` inside a string interpolates a CEL expression. A value that is",
		"*exactly* one `${...}` (nothing before or after) keeps its native type;",
		"otherwise every `${...}` is stringified and concatenated with the",
		"surrounding text. `$${` is a literal `${` (not an expression).",
		"",
		"```cel",
		"${inputs.city}",
		"Bearer ${env.TOKEN}",
		"order ${steps.create.out.orderId} for ${inputs.city}",
		"$${not-an-expr}",
		"```",
		"",
		"## Structured assertions",
		"",
		"`assert:` entries may be bare CEL, or one structured shorthand that",
		"compiles to the same CEL execution path (or, for `schema`, to the schema",
		"validator):",
		"",
		"| YAML | Compiles to |",
		"|---|---|",
		"| `status: 201` | `status == 201` |",
		"| `latency_ms: {lt: 2000}` | `latency_ms < 2000.0` (bounds combine with `&&`) |",
		"| `{path: body.riderId, eq: \"r1\"}` | `body.riderId == \"r1\"` |",
		"| `{path: body.riderId, exists: true}` | `has(body.riderId)` |",
		"| `{path: body.items[0], exists: true}` | `size(body.items) > 0` |",
		"| `{path: body.name, matches: \"^Q\"}` | `body.name.matches(\"^Q\")` |",
		"| `{path: body.tags, contains: \"x\"}` | `\"x\" in body.tags` |",
		"| `{schema: contract}` | validated against the response schema |",
		"",
		"## Loop blocks",
		"",
		"Inside a loop block's own nested-step expressions (not its `foreach`,",
		"checked once before any iteration): `iter.item` (the current element;",
		"unset for `repeat`) and `iter.index` (0-based). `steps.<id>` always",
		"resolves to that id's LATEST execution, so a nested step can read",
		"another nested step's value from the same iteration (if it already ran)",
		"or the previous one (guard with `has()`, same as a `when`-skipped step).",
		"After the loop, the block's own id has `count` (iterations run) and",
		"`iterations` (a list, one entry per iteration, each a map from nested",
		"step id to that iteration's `{request, status, headers, body,",
		"latency_ms, out}` -- bodies only up to 4MB total per block; past",
		"that, later iterations keep status/out but not request/body).",
		"",
		"```cel",
		"iter.item",
		"iter.index == 0",
		"steps.each.count == 3",
		"steps.each.iterations[0].create.status == 201",
		"```",
		"",
		"## Notes",
		"",
		"- A missing map key is an error, not `null`: `body.missing` fails with",
		"  \"no such key\" unless the key is present (possibly with value `null`).",
		"- `status`/`headers`/`body`/`latency_ms`/`request`/`out` are only",
		"  available inside the step that produced them; reference an earlier",
		"  step's response with `steps.<id>.body`, not `body`.",
		"- `iter` is only available inside a loop block's own nested-step",
		"  expressions; referencing a step that may not have run (a `when`, or",
		"  nesting inside a loop block) without a `has()`/`steps.?id` guard",
		"  gets a `MAYBE_SKIPPED` warning from `sapien flow validate`.",
		"- JSON integers decode as CEL ints (`2`), not doubles, so `body.count == 2`",
		"  works without a cast.",
		"- Structured `eq`/`neq` can't target a literal `null` (it's indistinguishable",
		"  from the field being unset); write `expr: \"body.x == null\"` instead.",
	}
	return strings.Join(lines, "\n") + "\n"
}
