package flow

import "strings"

// Reference returns a concise Markdown reference for the flow DSL, served
// by the MCP layer as get_dsl_reference("flow") (PLAN.md §23). It complements
// expr.Reference() ("expressions"), which covers the `${...}`/CEL language
// used inside a flow rather than the flow file shape itself.
func Reference() string {
	lines := []string{
		"# Flow DSL reference",
		"",
		"A flow is `*.flow.yaml`: an ordered list of API calls with input",
		"bindings and assertions. See `get_dsl_reference(\"expressions\")` for the",
		"`${...}`/CEL language used inside `input`, `body`, `headers`, `assert`,",
		"`extract`, and `until`.",
		"",
		"## Structure",
		"",
		"| Key | Meaning |",
		"|---|---|",
		"| `version` | Always `1`. Required. |",
		"| `id` | Flow ID. Defaults to the file name minus `.flow.yaml`. |",
		"| `name`, `description`, `tags` | Documentation only. |",
		"| `inputs` | Map of name -> `{type, required, default, description}`. |",
		"| `setup` | Ordered list of steps (§ below) that run before `steps`; optional. See \"Setup and teardown\". |",
		"| `steps` | Ordered list of steps (§ below). Required, at least one. |",
		"| `teardown` | Ordered list of steps (§ below) that always run after `steps`; optional. See \"Setup and teardown\". |",
		"",
		"## Step keys",
		"",
		"| Key | Meaning |",
		"|---|---|",
		"| `id` | Unique within the flow; `^[a-zA-Z_][a-zA-Z0-9_-]*$`. |",
		"| `call` | Operation ID, `<service>.<operationId>`. A step needs `call` or `example` (or both, if they agree). |",
		"| `example` | Saved example id to reuse; fills `call`/`input`/`body`/`headers` (§ below). |",
		"| `input` | Flat map bound by name to the operation's path/query/header params. |",
		"| `params` | `{path:, query:, headers:}`, for name collisions the flat `input:` can't express. |",
		"| `body` | Request body (any shape the operation expects). |",
		"| `headers` | Request headers; `${...}` values may use `secret.NAME`. |",
		"| `extract` | Map of name -> CEL over this step's own response; readable afterward as `steps.<id>.out.<name>`. |",
		"| `assert` | List of bare CEL or structured assertions (§ below). |",
		"| `until` | CEL; when present the step is retried until it evaluates true (or `poll.timeout` elapses). |",
		"| `poll` | `{interval: 1s, timeout: 30s}` (defaults shown); only used with `until`. |",
		"| `timeout` | Per-request timeout, e.g. `10s`. |",
		"",
		"## Input binding",
		"",
		"`input:` binds by parameter name against the operation's contract:",
		"path and query names match case-sensitively, header names",
		"case-insensitively. Every required parameter needs a value from",
		"`input` or `params`; a `${...}` template counts as provided even",
		"though its value isn't known until the step runs. `params.path`,",
		"`params.query`, and `params.headers` are validated the same way,",
		"against their specific location -- use them only when a name exists in",
		"more than one location and the flat form would be ambiguous.",
		"",
		"## Reusing an example",
		"",
		"A step may set `example: <id>` to reuse a request saved with",
		"`sapien example` (PLAN §34b) instead of writing `call`/`input`/",
		"`body`/`headers` out by hand. Resolution fills those four fields from",
		"the example before any other check runs; explicit step fields win:",
		"`call` must match the example's operation when both are set (else",
		"`EXAMPLE_OPERATION_MISMATCH`), `input` keys and `headers` merge per",
		"key with the step's value winning, and `body` on the step replaces",
		"the example's entirely rather than merging. `${...}` templates",
		"inside the example are kept and interpolated at run time exactly",
		"like a step's own.",
		"",
		"```yaml",
		"version: 1",
		"id: reuse-example",
		"inputs:",
		"  customerId: { type: string, required: true }",
		"steps:",
		"  - id: create",
		"    example: create-qcom-order      # fills call/input/body/headers",
		"    body: { customerId: \"${inputs.customerId}\" }  # replaces the example's body",
		"    assert:",
		"      - status == 201",
		"```",
		"",
		"## Setup and teardown",
		"",
		"`setup:`/`teardown:` are step lists shaped like `steps:`. `setup`",
		"runs first, then `steps`, then `teardown` -- always, even after a",
		"failure/error/cancellation, continuing past a teardown step's own",
		"failure. Teardown never changes the run's status or summary",
		"counts but is recorded on its own StepResult (`phase: teardown`).",
		"Ids are unique across all three lists; a step may reference any",
		"`setup` step plus earlier steps in its own list; `setup`/`steps`",
		"may not reference `teardown`; `teardown` may reference any",
		"`setup` or `steps` step.",
		"",
		"```yaml",
		"version: 1",
		"setup:",
		"  - id: create",
		"    call: order-service.createOrder",
		"    body: { customerId: cust_1, type: QCOM,",
		"            pickup: { lat: 1, lng: 2 }, drop: { lat: 1, lng: 2 } }",
		"    extract: { orderId: body.orderId }",
		"steps:",
		"  - id: allocate",
		"    call: allocation-service.allocate",
		"    body: { orderId: \"${steps.create.out.orderId}\" }",
		"    extract: { allocationId: body.allocationId }",
		"teardown:",
		"  - id: release",
		"    call: allocation-service.releaseAllocation",
		"    input: { allocationId: \"${steps.allocate.out.allocationId}\" }",
		"```",
		"",
		"## Expression roots by context",
		"",
		"`inputs`, `env`, and `steps.<id>.{request,status,headers,body,",
		"latency_ms,out}` are available everywhere. `status`, `headers`,",
		"`body`, `latency_ms`, `request`, and `out` (without a `steps.<id>.`",
		"prefix) refer to *this* step's own attempt and are therefore only",
		"available inside that same step's `assert`, `extract`, and `until`",
		"-- not in its own `input`/`body`/`headers` (the request hasn't been",
		"made yet). `secret.NAME` may only appear inside `headers` or",
		"`params.headers` values.",
		"",
		"## Structured assertions",
		"",
		"Shorthand for a common CEL comparison; see `get_dsl_reference(\"expressions\")`",
		"for the full compilation table. The most common:",
		"",
		"| YAML | Meaning |",
		"|---|---|",
		"| `status: 201` | Response status equals 201. |",
		"| `latency_ms: {lt: 2000}` | Response latency under 2000ms (`lt`, `lte`, `gt`, `gte`). |",
		"| `{path: body.riderId, eq: \"r1\"}` | `body.riderId == \"r1\"`. |",
		"| `{path: body.riderId, exists: true}` | The field is present. |",
		"| `schema: contract` | Validate the body against the response schema. |",
		"| `{expr: \"body.total > 0\"}` | A bare CEL assertion in object form, so `message`/`soft` can be added to it. |",
		"",
		"Any assertion form may add `message:` to name the assertion in a",
		"failure report, and `soft: true` to warn instead of fail (§ below).",
		"",
		"`eq`, `neq`, `contains`, and `matches` (when it is itself a template)",
		"accept `${...}` just like `input`/`body`/`headers`, keeping the",
		"interpolated value's native type: `{path: body.riderId, eq:",
		"\"${steps.allocate.out.riderId}\"}` compares against the rider ID that",
		"step actually extracted, not the literal template text.",
		"",
		"## Soft assertions",
		"",
		"`soft: true` on any assertion form -- bare `expr:`, structured, or",
		"`schema:` -- records a mismatch as a warning on the step instead of",
		"failing it. The step and the run stay green, the result is kept",
		"(`soft: true, passed: false`), and the run summary counts it under",
		"`assertions_warned` rather than `assertions_failed`. Use it for a check",
		"worth tracking but not worth failing a run over: a value expected to",
		"drift, a latency budget still under observation, a field being rolled",
		"out, an upstream behaviour you are watching but do not own.",
		"",
		"```yaml",
		"version: 1",
		"id: soft-assertions",
		"steps:",
		"  - id: allocate",
		"    call: allocation-service.allocate",
		"    body: { orderId: ord_1 }",
		"    assert:",
		"      - status == 201                       # hard: a mismatch fails the run",
		"      - { path: body.status, eq: ASSIGNED, soft: true,",
		"          message: \"allocation should land ASSIGNED, not PENDING\" }",
		"      - { expr: \"latency_ms < 500\", soft: true }",
		"```",
		"",
		"Each run compares its soft results with the most recent earlier run of",
		"the same flow and reports every flip: `soft mismatch:` lines and `soft",
		"assertion now passing since run <id>:`, printed by `sapien flow run`,",
		"`sapien run resume`, and returned by `run_flow`. A soft assertion is",
		"how a flow tracks something it does not control without going red.",
		"",
		"## Worked example",
		"",
		"```yaml",
		"version: 1",
		"id: order-allocation",
		"name: Order allocation",
		"description: Create an order, allocate a rider, verify the rider is online.",
		"tags: [allocation, smoke]",
		"",
		"inputs:",
		"  customerId: { type: string, default: \"cust_123\" }",
		"  city:       { type: string, required: true }",
		"",
		"steps:",
		"  - id: create",
		"    call: order-service.createOrder",
		"    body:",
		"      customerId: \"${inputs.customerId}\"",
		"      type: QCOM",
		"      pickup: { lat: 12.9716, lng: 77.5946 }",
		"      drop: { lat: 12.9352, lng: 77.6146 }",
		"    extract:",
		"      orderId: body.orderId",
		"    assert:",
		"      - status == 201",
		"",
		"  - id: allocate",
		"    call: allocation-service.allocate",
		"    body: { orderId: \"${steps.create.out.orderId}\" }",
		"    extract:",
		"      riderId: body.riderId",
		"    assert:",
		"      - status == 201",
		"      - latency_ms < 2000",
		"",
		"  - id: rider",
		"    call: rider-service.getRider",
		"    input: { riderId: \"${steps.allocate.out.riderId}\" }",
		"    assert:",
		"      - status == 200",
		"      - body.online == true",
		"      - { path: body.qcomSkill, eq: true, message: \"QCOM riders must have qcomSkill\" }",
		"      - { path: body.riderId, eq: \"${steps.allocate.out.riderId}\" }",
		"```",
		"",
		"## Polling example",
		"",
		"```yaml",
		"version: 1",
		"id: poll-allocation",
		"steps:",
		"  - id: allocate",
		"    call: allocation-service.allocate",
		"    body: { orderId: ord_1 }",
		"    extract:",
		"      allocationId: body.allocationId",
		"",
		"  - id: wait",
		"    call: allocation-service.getAllocation",
		"    input: { allocationId: \"${steps.allocate.out.allocationId}\" }",
		"    until: status == 200 && body.riderId != null",
		"    poll: { interval: 1s, timeout: 10s }",
		"    assert:",
		"      - status == 200",
		"```",
		"",
		"## Diagnostic codes",
		"",
		"Every diagnostic has `code`, `severity`, `message`, and where possible",
		"`line` and `suggestions` (PLAN.md §23.1). Warnings never make a flow",
		"invalid.",
		"",
		"| Code | Meaning |",
		"|---|---|",
		"| `FLOW_VERSION` | `version` is missing or isn't `1`. |",
		"| `NO_STEPS` | `steps` is missing or empty. |",
		"| `RESERVED_KEY` | Key parked for a future DSL version (`when`, `parallel`, `foreach`, `retry`, `use`, `needs`, `datasets`). |",
		"| `UNKNOWN_KEY` | Key not recognized anywhere in the schema. |",
		"| `SCHEMA` | Any other schema violation. |",
		"| `STEP_ID_INVALID` | A step's `id` doesn't match the id pattern. |",
		"| `STEP_ID_DUPLICATE` | Two steps share the same `id`. |",
		"| `UNKNOWN_OPERATION` | `call` names an operation not in the catalog. |",
		"| `DEPRECATED_OPERATION` | `call` names an operation marked deprecated. |",
		"| `UNKNOWN_INPUT_NAME` | An `input`/`params.*` key isn't a param of `call`. |",
		"| `MISSING_REQUIRED_PARAM` | A required param has no value. |",
		"| `MISSING_BODY` | The operation requires a body and none was given. |",
		"| `UNEXPECTED_BODY` | A body was given but the operation takes none. |",
		"| `UNKNOWN_BODY_FIELD` | A top-level body key isn't in the operation's request schema. |",
		"| `EXPR_SYNTAX` | A `${...}`/assert/extract/until expression doesn't parse. |",
		"| `UNKNOWN_STEP` | `steps.<id>` names a step that doesn't exist. |",
		"| `STEP_ORDER` | `steps.<id>` names a step that runs at or after this one. |",
		"| `UNKNOWN_FLOW_INPUT` | `inputs.<name>` isn't declared in `inputs:`. |",
		"| `CONTEXT_ROOT` | `status`/`headers`/`body`/`latency_ms`/`request`/`out` used outside this step's own `assert`/`extract`/`until`. |",
		"| `SECRET_CONTEXT` | `secret.NAME` used outside `headers`/`params.headers`. |",
		"| `UNKNOWN_FIELD` | A `body.*` path isn't in the called operation's response shape. |",
		"| `ASSERTION_INVALID` | A structured assertion is empty, ambiguous, or malformed. |",
		"| `DUPLICATE_EXTRACT` | Two `extract:` entries in one step share a name. |",
		"| `INVALID_DURATION` | `timeout`/`poll.interval`/`poll.timeout` isn't a valid duration (e.g. `1500ms`, `30s`, `2m`). |",
		"| `UNKNOWN_EXAMPLE` | `example` names an id the resolver doesn't know. |",
		"| `EXAMPLE_OPERATION_MISMATCH` | `call` and `example` are both set but name different operations. |",
	}
	return strings.Join(lines, "\n") + "\n"
}
