package flow

import "strings"

// UIReference returns the Markdown reference for ui steps, served as
// get_dsl_reference("ui"). It is its own topic, rather than a section of
// Reference(), so the flow reference stays agent-sized for the flows that
// never touch a device.
func UIReference() string {
	lines := []string{
		"# UI steps reference",
		"",
		"",
		"A step with `ui:` drives a mobile app on a local Android emulator (through",
		"Appium) instead of calling an operation, so one flow can mix API calls",
		"and app interactions and pass values between them. `ui.app` names an",
		"entry of the environment file's `apps:` map (package, APK, build",
		"command, log format). Every ui step in a run shares one device",
		"session, so a step continues from the screen the previous one left.",
		"A ui step takes `id`, `when`, `extract`, `assert`, and `timeout`",
		"like a call step, but no request fields (`UI_SHAPE`).",
		"",
		"```yaml",
		"version: 1",
		"id: rider-login",
		"inputs:",
		"  phone: {type: string, default: \"8445544024\"}",
		"  otp: {type: string, default: \"000000\"}",
		"steps:",
		"  - id: login",
		"    ui:",
		"      app: rider",
		"      actions:",
		"        - launch: {clear_state: true}",
		"        - type: {hint: Enter mobile number, text: \"${inputs.phone}\"}",
		"        - tap: {text: Get OTP}",
		"        - type: {hint: \"000000\", text: \"${inputs.otp}\"}",
		"        - wait_for: {id: home_screen, timeout: 30s}",
		"        - read: {id: rider_name, as: name}",
		"        - assert_visible: {text_contains: Online}",
		"    assert:",
		"      - \"body.logs.api.exists(c, c.path.endsWith('/auth') && c.status == 200)\"",
		"      - {path: out.name, exists: true}",
		"    extract:",
		"      auth_calls: \"body.logs.api.filter(c, c.path.endsWith('/auth')).size()\"",
		"```",
		"",
		"Actions run in order; the first that fails fails the step (a screenshot",
		"and the page source are saved as step artifacts). Each is a one-key",
		"mapping, or a bare word for `back`/`stop`/`launch`/`screenshot`/`hide_keyboard`:",
		"",
		"| Action | Arguments |",
		"|---|---|",
		"| `launch` | `clear_state` (wipe app data first), `grant_permissions` (default true). Installs/updates the APK first if needed. |",
		"| `stop` | Force-stops the app. |",
		"| `deeplink` | `url` (or a plain string), e.g. `kaptaan://home`. |",
		"| `tap` | Selector. |",
		"| `type` | `text` to type, into the element given by an inline `id`/`hint`/`text_contains`/`xpath` or `into: {text: ...}`; `clear: true` empties it first. |",
		"| `clear` | Selector. |",
		"| `swipe` | `direction` up/down/left/right: across the screen, or with a selector across that element (a slide-to-confirm button). |",
		"| `hide_keyboard` | Closes the soft keyboard (no-op when it is down); some screens act only once it closes. |",
		"| `scroll_to` | Selector, `direction` (default down), `max_swipes` (default 10): swipes until the element is on screen. |",
		"| `back` | Presses Android back. |",
		"| `wait_for` | Selector, `timeout` (default 10s), `gone: true` to wait for it to disappear. |",
		"| `read` | Selector, `as`: the element's text becomes `out.<as>`. |",
		"| `screenshot` | Optional `name` (or a plain string); saved as a step artifact. |",
		"| `assert_visible` / `assert_not_visible` | Selector, `timeout`, `message`. Recorded as an assertion on the step. |",
		"| `assert_text` | Selector plus exactly one of `eq`/`contains`/`matches`, `message`. |",
		"",
		"A selector is exactly one of `id` (a Flutter `Semantics(identifier:)`,",
		"i.e. Android resource-id, falling back to the accessibility label),",
		"`text`, `text_contains`, `hint` (a text field's hint), or `xpath`,",
		"plus an optional 0-based `index`. Element lookups retry until their",
		"`timeout` (default 10s). String arguments accept `${...}` templates.",
		"",
		"Inside the ui step's own `assert`/`extract` (and as `steps.<id>.*`",
		"later): `out` holds `read` results and extracts; `body.logs.api` is",
		"the app's network calls parsed from logcat during this step, each",
		"`{method, url, path, status, request: {headers, body}, response: {body}}`",
		"(needs a debug build and the app's `log_format`); `body.logs.lines`",
		"is the raw log lines; `body.screen.activity` is the foreground",
		"activity; `body.actions` lists each action's outcome. `status` is 0.",
		"",
		"## Diagnostic codes",
		"",
		"| Code | Meaning |",
		"|---|---|",
		"| `UI_SHAPE` | A ui step also sets `call`/`example` or a request field (input/params/body/headers/until/poll), or lacks `ui.app`/`ui.actions`. |",
		"| `UI_ACTION` | An action is unknown, sets more than one selector, lacks a selector it needs (or sets one it takes none of), or misses its own arguments (`url`, `text`, `direction`, `as`, one of `eq`/`contains`/`matches`). |",
		"| `INVALID_DURATION` | An action's `timeout` isn't a duration. |",
		"",
		"## Setup on this machine",
		"",
		"Run `sapien device doctor`: it checks Node, Appium and its uiautomator2",
		"driver, ANDROID_HOME, JAVA_HOME, adb, and the emulator, and prints the",
		"fix for each gap. `sapien device snapshot` (add `--json` for agents) lists",
		"every selector on the current screen with the value to write for it;",
		"`sapien device build <app>` rebuilds and installs. Per-machine settings",
		"live in `.sapien/ui.yaml`: `appium_url`, `auto_start_appium`, `avd` (booted",
		"when no device is attached), `serial`, `attach` (apps already running",
		"under `flutter run`: never built, installed, or cleared; also",
		"`sapien flow run --attach <app>`), and `repos` (per-machine `repo:`).",
		"",
		"## Apps",
		"",
		"An environment file lists the apps its ui steps can drive:",
		"",
		"| Key | Meaning |",
		"|---|---|",
		"| `package` | Android application id. Required. |",
		"| `repo` | Source checkout, relative to the workspace root or absolute. |",
		"| `build` | Shell command run in `repo` when the APK is missing (or with `--rebuild`). |",
		"| `apk` | Built APK, relative to `repo`; installed when it changed since the last install. |",
		"| `log_format` | `rider-box`, `overwatch-api-logger`, or `raw`: how `body.logs.api` is parsed. |",
		"| `log_tag` | Logcat tag to capture (default `flutter`). |",
		"| `permissions` | Runtime permissions `launch` grants, e.g. `ACCESS_FINE_LOCATION`. |",
		"",
		"Network logs only exist in debug builds, so `build` should produce one.",
	}
	return strings.Join(lines, "\n") + "\n"
}
